# Generated by Django 4.2.4 on 2023-08-30 10:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="Comment",
            new_name="comment",
        ),
    ]
